### ISSUE TITLE
Is there any way to embed a asciinema in a README.md?

### ISSUE THREAD

**Issue by Unitech** [asciinema/discussions#283]
I tried to embed the script into the README of PM2 (https://github.com/Unitech/PM2) without success. I think Github avoid inserting scripts to avoid XSS attacks, but maybe there is another way to do it ?

Thanks for asciinema !

**Comment by ku1ik** [comment]
@markvanderloo in short: it's not possible to embed the player in README (Github doesn't allow script execution), but you can embed PNG preview which links to the recording on asciinema.org. See https://docs.asciinema.org/manual/server/embedding/

**Comment by DanielBiegler** [comment]
I am aware that this is a closed issue but I just got here through a search engine so I'll contribute in case others arrive here as well.

### How to make it work in 2025

Run your recording session with the v2 format instead of the newer v3 because `svg-term-cli` only supports v2

```bash
asciinema rec -f asciicast-v2  # ... your other args
# or convert existing animation to v2 format
asciinema convert -f asciicast-v2  # ... your other flags
```

Use the here mentioned `svg-term-cli` to generate an svg:

```bash
npx svg-term-cli < usage-demo.json > usage-demo.svg  # ... your other flags
```

It works :)

![Image](https://github.com/user-attachments/assets/9c849000-953d-4258-ac94-f7444251c5f3)
